version: '3.8'
networks:
  my_net_bot:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

services:
  imagen-captcha1:
    image: imagen:latest
    container_name: imagen-captcha1
    ports:
      - "9000:9000"  # Mapea el puerto 9000 del host al puerto 9000 del contenedor
    environment:
      - PORT=9000
      - HOST=0.0.0.0
    restart: always
    networks:
      my_net_bot:
        ipv4_address: 172.18.0.2

  imagen-captcha2:
    image: imagen:latest
    container_name: imagen-captcha2
    ports:
      - "9001:9001"  # Mapea el puerto 9000 del host al puerto 9000 del contenedor
    environment:
      - PORT=9001
      - HOST=0.0.0.0
    restart: always
    networks:
      my_net_bot:
        ipv4_address: 172.18.0.3

  identificador1:
    image: identificador:latest
    container_name: identificador1
    restart: always
    ports:
      - "3001:3001"
    networks:
      my_net_bot:
        ipv4_address: 172.18.0.5
    environment:
      - HOST=0.0.0.0
      - PORT=3001
      - API_IMAGE=http://172.18.0.2:9000/api/service/image/translate
      - CONCURRENCY_LIMIT=15
      - RETRIES=100
      - ENTIDAD=30
      - ANIO=2023
      - START=0000001
      - FINISH=0099999
      - DB_DATABASE=identificadores
      - DB_HOST=192.168.1.120
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_STORE=folios
      - BOT_ID=8
      - STATUSBOT=bot1

  identificador2:
    image: identificador:latest
    container_name: identificador2
    restart: always
    ports:
      - "3002:3002"
    networks:
      my_net_bot:
        ipv4_address: 172.18.0.6
    environment:
      - HOST=0.0.0.0
      - PORT=3002
      - API_IMAGE=http://172.18.0.3:9001/api/service/image/translate
      - CONCURRENCY_LIMIT=15
      - RETRIES=100
      - ENTIDAD=30
      - ANIO=2023
      - START=0000001
      - FINISH=0099999
      - DB_DATABASE=identificadores
      - DB_HOST=192.168.1.120
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_STORE=folios
      - BOT_ID=8
      - STATUSBOT=bot2