version: '3.8'
networks:
  my_net_bot_test:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16
          gateway: 172.16.0.1

services:
  imagen-captcha1:
    image: imagen:latest
    container_name: imagen-captcha_test1
    ports:
      - "9012:9012"
    environment:
      - PORT=9012
      - HOST=0.0.0.0
    restart: always
    networks:
      my_net_bot_test:
        ipv4_address: 172.16.0.2

  imagen-captcha2:
    image: imagen:latest
    container_name: imagen-captcha_test2
    ports:
      - "9011:9011"
    environment:
      - PORT=9011
      - HOST=0.0.0.0
    restart: always
    networks:
      my_net_bot_test:
        ipv4_address: 172.16.0.3

  identificador1:
    image: identificador:latest
    container_name: identificador_test1
    restart: always
    ports:
      - "9013:9013"
    networks:
      my_net_bot_test:
        ipv4_address: 172.16.0.5
    environment:
      - HOST=0.0.0.0
      - PORT=9013
      - API_IMAGE=http://172.16.0.2:9012/api/service/image/translate
      - CONCURRENCY_LIMIT=15
      - RETRIES=100
      - ENTIDAD=30
      - ANIO=2023
      - START=0000001
      - FINISH=0099999
      - DB_DATABASE=identificadores
      - DB_HOST=192.168.1.120
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_STORE=folios
      - BOT_ID=8
      - STATUSBOT=bot1
    volumes:
      - identificador1_data:/data
      - /path/on/host:/app/

  identificador2:
    image: identificador:latest
    container_name: identificador_test2
    restart: always
    ports:
      - "9014:9014"
    networks:
      my_net_bot_test:
        ipv4_address: 172.16.0.6
    environment:
      - HOST=0.0.0.0
      - PORT=9014
      - API_IMAGE=http://172.16.0.3:9011/api/service/image/translate
      - CONCURRENCY_LIMIT=15
      - RETRIES=100
      - ENTIDAD=30
      - ANIO=2023
      - START=0000001
      - FINISH=0099999
      - DB_DATABASE=identificadores
      - DB_HOST=192.168.1.120
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_STORE=folios
      - BOT_ID=8
      - STATUSBOT=bot2
    volumes:
      - identificador2_data:/data
      - /path/on/host:/app/

volumes:
  identificador1_data:
  identificador2_data:
